#ifndef LIBSYNEXENS3_VERSION_IN_H
#define LIBSYNEXENS3_VERSION_IN_H

#define LIBSYNEXENS3_MAJOR 0
#define LIBSYNEXENS3_MINOR 1
#define LIBSYNEXENS3_REVISION 3

#define LIBSYNEXENS3_BUILD "202207041636"
#define LIBSYNEXENS3_BUILD_TIMESTAMP_YEAR 2022
#define LIBSYNEXENS3_BUILD_TIMESTAMP_MON 07
#define LIBSYNEXENS3_BUILD_TIMESTAMP_DAY 04
#define LIBSYNEXENS3_BUILD_TYPE "alpha"


#define LIBSYNEXENS3_RECOMMENDED_FIRMWARE_VERSION_MAJOR 0
#define LIBSYNEXENS3_RECOMMENDED_FIRMWARE_VERSION_MINOR 6
#define LIBSYNEXENS3_RECOMMENDED_FIRMWARE_VERSION_REVISION 1
#define LIBSYNEXENS3_RECOMMENDED_FIRMWARE_VERSION_TIMESTAMP "20220629"

#endif


